---
version: '3.3'
services:
  discord-auth-server:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "${HOST}:${PORT}:${PORT}"
    env_file:
      - stack.env
